describe("Home grid images", () => {
  beforeEach(() => {
    cy.visit("http://localhost:3000");
  });

  it("should display three cat images", () => {
    cy.get(".grid").find("img").should("have.length", 3);
  });

  it("should display the first cat image with correct attributes", () => {
    cy.get(".grid img")
      .eq(0)
      .should("have.attr", "alt", "Image of a cat generated by IA");
  });

  it("should display the second cat image with correct attributes", () => {
    cy.get(".grid img")
      .eq(1)
      .should("have.attr", "alt", "Image of a cat generated by IA");
  });

  it("should display the third cat image with correct attributes", () => {
    cy.get(".grid img")
      .eq(2)
      .should("have.attr", "alt", "Image of a cat generated by IA");
  });
});
