<template>
  <div
    class="grid grid-cols-8 grid-rows-2 gap-2 w-full aspect-video md:w-[500px] shrink-0"
  >
    <NuxtImg
      src="/images/kitty1.webp"
      alt="Image of a cat generated by IA"
      class="rounded-lg h-full w-full row-span-2 col-span-8 md:col-span-5 object-cover"
    />
    <NuxtImg
      src="/images/kitty2.webp"
      alt="Image of a cat generated by IA"
      class="rounded-lg h-full w-full col-span-4 md:col-span-3 object-cover"
    />
    <NuxtImg
      src="/images/kitty3.webp"
      alt="Image of a cat generated by IA"
      class="rounded-lg h-full w-full col-span-4 md:col-span-3 object-cover"
    />
  </div>
</template>

<script>
export default {
  name: "CatImageGrid",
};
</script>
